### ISSUE TITLE
Segfault with latest changes on large files

### ISSUE THREAD

**Issue by charles-randall** [mayank-02/msort#11]
Input file attached...

```
$ /tmp/msort.new uuid.10k.txt > /dev/null
Segmentation fault (core dumped)
```
Backtrace,
```
$ gdb /tmp/msort.new core
...
Reading symbols from /tmp/msort.new...
[New LWP 2773816]
Core was generated by `/tmp/msort.new uuid.10k.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056143a4bedf6 in merge (f1=<error reading variable: Cannot access memory at address 0x7ffe1f355de8>, 
    f2=<error reading variable: Cannot access memory at address 0x7ffe1f355de0>, 
    f3=<error reading variable: Cannot access memory at address 0x7ffe1f355dd8>) at msort.c:751
751	void merge(FILE *f1, FILE *f2, FILE *f3) {
...
(gdb) bt
#0  0x000056143a4bedf6 in merge (f1=<error reading variable: Cannot access memory at address 0x7ffe1f355de8>, 
    f2=<error reading variable: Cannot access memory at address 0x7ffe1f355de0>, 
    f3=<error reading variable: Cannot access memory at address 0x7ffe1f355dd8>) at msort.c:751
#1  0x000056143a4bf789 in handleMerges (numFiles=3, x=114 'r') at msort.c:957
#2  0x000056143a4bffef in main (argc=2, argv=0x7ffe20356568) at msort.c:1182

```
[uuid.10k.txt](https://github.com/mayank-02/msort/files/6184937/uuid.10k.txt)

**Comment by charles-randall** [comment]
Probably the same problem as issue #7
